
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://buizhanvxiykyapyndsh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1aXpoYW52eGl5a3lhcHluZHNoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODQ0ODEsImV4cCI6MjA2MjY2MDQ4MX0.ZbZdseqe4ePsHDMQGmmB_cFrzP0Zp0Pi0A7AAjfDmTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      storageKey: 'mkranker-supabase-auth-token'
    }
  }
);
